export interface IPostBlog{
    email:string;
    title: string;
    tags : string[];
    content: string;
}

// Generated by https://quicktype.io

export interface IListBlogs {
    data:    Datum[];
    total:   number;
    nexPage: number;
}

export interface Datum {
    _id:      string;
    title:    string;
    tags:     Tag[];
    createAt: string;
    updateAt: string;
    user:     User;
}

export interface User {
    _id:           string;
    name:          string;
    email:         string;
    image:         string;
    emailVerified: null;
}

export interface Tag {
    _id:string;
    tageLabel: string
}

// Generated by https://quicktype.io

export interface ISingleblog {
    _id:      string;
    title:    string;
    content:  string;
    createAt: string;
    updateAt: string;
    user:     User;
    tags:     Tag[];
}

export interface Tag {
    _id:       string;
    tageLabel: string;
}

export interface User {
    _id:           string;
    name:          string;
    email:         string;
    image:         string;
    emailVerified: null;
}

