import "./globals.css";
import Providers from "@/providers/index";
import "suneditor/dist/css/suneditor.min.css";
import 'react-loading-skeleton/dist/skeleton.css'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <Providers>
      <html lang="en" data-mode="light">
        {children}
      </html>
    </Providers>
  );
}
